name: Pull request

on:
  pull_request:

jobs:
  build-pullrequest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      # access it through ${{ steps.get_version.outputs.VERSION }}
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.2'
    - name: install R packages
      run: |
        sudo apt-get install -y texlive-latex-base texlive texlive-fonts-extra texinfo qpdf
        sudo Rscript -e "install.packages(c('curl', 'xml2', 'httr', 'devtools', 'testthat', 'knitr', 'rmarkdown', 'roxygen2', 'e1071', 'survival'), repos='https://cloud.r-project.org/')"
      env:
        DEBIAN_FRONTEND: noninteractive
        DEBCONF_NONINTERACTIVE_SEEN: true
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Apply Patch
      run: |-
        # Remove -s option of tini. while gvisor does not support PR_SET_CHILD_SUBREAPER
        sed -i 's/tini -s/tini/' $SPARK_ENTRYPOINT

        cp -f .staroid/Dockerfile $BASE_DOCKERFILE
        cp -f .staroid/Dockerfile_python $PYTHON_DOCKERFILE
        cp -f .staroid/Dockerfile_r $R_DOCKERFILE

        # print
        cat $SPARK_ENTRYPOINT
      env:
        SPARK_ENTRYPOINT: resource-managers/kubernetes/docker/src/main/dockerfiles/spark/entrypoint.sh
        BASE_DOCKERFILE: resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile
        PYTHON_DOCKERFILE: resource-managers/kubernetes/docker/src/main/dockerfiles/spark/bindings/python/Dockerfile
        R_DOCKERFILE: resource-managers/kubernetes/docker/src/main/dockerfiles/spark/bindings/R/Dockerfile
    - name: Build distribution
      run: |-
        pip install wheel
        ./dev/make-distribution.sh --name spark --pip --r --tgz -Psparkr -Phadoop-2.7 -Phive -Phive-thriftserver -Pkubernetes
      env:
        DEBIAN_FRONTEND: noninteractive
        DEBCONF_NONINTERACTIVE_SEEN: true
    - name: Build docker image
      run: |-
        ./bin/docker-image-tool.sh \
        -r opendatastudio \
        -t test \
        -p kubernetes/dockerfiles/spark/bindings/python/Dockerfile \
        -R kubernetes/dockerfiles/spark/bindings/R/Dockerfile \
        build
      working-directory: ./dist
    - name: Push image
      run: |-
        docker images
